#!/usr/bin/env bash
# UFW commands used to block all incoming traffic except SSH, HTTP, and HTTPS
sudo apt-get update
sudo apt-get install -y ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
