#!/usr/bin/env bash
# Installs and configures Nginx to serve a page containing "Holberton School"
apt-get update
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

service nginx start
