#!/usr/bin/env bash
# Installs Nginx, sets up redirection, and a custom 404 page
apt-get update
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/listen 80 default_server/a\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sed -i '/location \/ {/i\\terror_page 404 /404.html;' /etc/nginx/sites-available/default

service nginx restart
